[project]
ref = "decarrerita-local"
name = "decarrerita"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
password = "postgres"

[auth]
enabled = true

[storage]
enabled = false

[inbucket]
enabled = false
